### ISSUE TITLE
How to adjust the lead for the next highlight?

### ISSUE THREAD

**Issue by markadrake** [eddiemf/vue-scrollactive#17]
_Nice package! Thank you for writing it - it has saved me some time and trouble from writing my own._

I'm hoping my feedback is constructive. I'd like to discuss a couple of things I ran into when implementing this in a new client site. I added a CodePen example to follow along with here: https://codepen.io/markadrake/pen/xWebxQ

## I want to highlight the next item as soon as it's visible 

Meaning, once section two has scrolled into view then "two" should highlight in the menu. This too could benefit from an offset so that we can say "once this element is at least 100px visible, time to switch the active class". 

There's already an offset parameter, and it works well when clicking a link and scrolling to the desired element on the page. But I need control over when highlighting occurs and quite possibly, an offset value of its own.

## Unit options for the offset

Currently the offset isn't just a number value - it's a specific number of pixels. However, in implementation I may want more control over this value especially when considering the design changes that can occur between breakpoints, and the user's zoom level. It would be nice to provide different values such as:

- A percentage (50%)
- An em/rem value (4rem)

Or even take a targe element, calculate it's height, and use that as the value or part of the calculation of the value. This would have to subscribe to the window resize event to keep it in check.

## What's causing the bounce back between items on the page?

Click on "Six" and you should see it jump back to five. After a while of testing, you may notice other items in the menu will start to behave this way - but "Six" does it everytime. 

Although I couldn't replicate it any more here, in a site I'm building and using this on it's even more pronounced as all of the menu items scroll to the right place, set the appropriate highlight, but after the scroll animation is complete it will highlight the previous entry instead.

**Comment by eddiemf** [comment]
Hello @markadrake, thanks for the compliment! And sorry for the response time, I just relocated to another country and was completely off from Github for a time.

Your first change is pretty major, but it looks nice and makes a lot of sense in some contexts. I'll certainly add it in the release version.

Regarding your second change, I'm not sure if that would make much sense in the current implementation. Take this line of code as example:

`const isScreenPastSection = window.pageYOffset >= this.getOffsetTop(target) - this.offset;`

You can see that the offset is used as a value only, and it needs to be in `px` because that's the unit I'm dealing with when getting `window.pageYOffset` and `this.getOffsetTop()` values. If it was in percentage, would it be relative to what? And how would I be able to calculate the value to offset if it was in `em` or `rem`? 

I think you should probably calculate this before setting the value, so you can make your own breaking points and change the value as you want. Maybe we can think of a responsive option too, but I'm not sure how that would work, tell me if you have any ideas on that.

And finally about the bug you described, it's not happening in my browser, which browser were you testing it? Maybe it's a browser related bug since I click the Six and it works perfectly. But regarding your implementation on your site, try to make sure you don't have any margin between the sections because that messes with the offset and usually leads to undesired behavior. If you need spacing between the sections then just use a padding, not margin.

Feel free to ask anything and to give feedback on new features as you did, it helps a lot since I basically always use this plugin in a very simple way, and sometimes people need features that I would never think about.

Thanks again!

**Comment by harrymee123** [comment]
The offset works perfectly for making the next section link active earlier. The bit that makes it not usable is when you click a link, it scrolls to the element including the offset. 

Would it be simpler to split the offset in to two separate offsets. 

A 'scroll to offset' that is used when you click a link. Leaving an offset above the element.

And..
 
A 'active trigger offset' that will offset the distance above an element which will trigger its link to be active.

**Comment by eddiemf** [comment]
Hello guys, I've recently added a new prop called `scrollOffset` to control the offset when clicking to scroll, this way you can now use `offset` to control when the element will be active while scrolling and `scrollOffset` to set offset when clicking to scroll. 

Regarding the described bug, as I've said I couldn't reproduce it in my environment, but feel free to open the issue again if needed, I'll be happy to help :)
