### ISSUE TITLE
Scrolling does not change the hash of the url

### ISSUE THREAD

**Issue by wellfrog16** [eddiemf/vue-scrollactive#52]
only change the hash by click

**Comment by justinriggio** [comment]
@wellfrog16 did you find a workaround for this? Having the same issue.

**Comment by Psychokrameur** [comment]
also interested!

**Comment by pinkman-frontend-user** [comment]
```pug
       scrollactive.nav(
          @itemchanged="onItemChanged"
        )
```


```
  methods: {
   onItemChanged(event, item) {
      if (item) {
        history.pushState(null, null, item.href)
      }
    }
}
```

**Comment by Axieum** [comment]
Push whitespace to remove the anchor from the url
```js
history.pushState(null, null, current ? current.href : ' ')
```
_**Note**: this does not preserve page queries (i.e. `?q=query+param`)_

**Comment by Axieum** [comment]
I recommend against modifying the history outside of Vue Router as it interferes with the browser's back button and history.

**Comment by eddiemf** [comment]
I'm not sure if it makes sense to have this as a feature. It's how browsers have worked since forever and I think it's almost always not the intended behaviour. 

If you really want to have this behaviour for some reason you can always resort to the `itemchanged` event and implement it yourself as @pinkman-frontend-user mentioned.

**Comment by Axieum** [comment]
I believe the intentions behind this feature is for the URL to reflect the point at which the user has scrolled to. Thereby allowing them to copy the URL at any point. But yes, I do think this is a minor feature.
