### ISSUE TITLE
vue-scrollactive inside a viutify dialog doesn't work

### ISSUE THREAD

**Issue by JorgeMantillaHernandez** [eddiemf/vue-scrollactive#68]
hi, i am trying to use vue-scrollactive inside a viutify dialog / modal but it doesn't work. I think it doesn't iterate over the dialogue.

try scrollContainerSelector but it doesn't work either.

I want to clarify that if it works for me outside the dialog / modal

also when I click on an <a> it doesn't work either

could you help me please? thanks!

![image](https://user-images.githubusercontent.com/65055035/83335396-20e3e880-a272-11ea-87b5-c01205aca194.png)

**Comment by eddiemf** [comment]
It's hard to tell without any live example or any error. 

What do you mean by doesn't work? Does it throw any error on console? 

As far as I see it should be able to work inside of this dialog component without problems, but if you give me some error it might be easier to track the problem.

If there's no error at all it would be nice if you could replicate the problem in a sandbox like JSFiddle or even create a repo with the problem so that I can take a closer look at it.

**Comment by JorgeMantillaHernandez** [comment]
thanks for replying :) 
I have uploaded an example to a repository, with normal use and use within the dialog

![image](https://user-images.githubusercontent.com/65055035/83339038-6c58bf80-a28f-11ea-84b6-159fc231190a.png)

https://github.com/JorsMantilla9/scroll-vue-demo

thanks for your help

**Comment by eddiemf** [comment]
Thanks for the demo :)

Looks like you're just using the wrong element in `scrollContainerSelector`, it should be `.v-dialog` (the one that has the `overflow: auto`) and not `.v-dialog__content` as you're doing.

**Comment by JorgeMantillaHernandez** [comment]
is working! thanks Bro
